name: esalat_car
description: "اپلیکیشن اصالت خودرو"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # پکیج‌های اضافه شده برای پروژه شما
  http: ^1.2.1                  # برای ارتباط با API سرور
  shared_preferences: ^2.2.3    # برای ذخیره کوکی/توکن لاگین
  provider: ^6.1.2              # برای مدیریت تم تاریک/روشن
  sqflite: ^2.3.0               # برای دیتابیس آفلاین (ثبت خودرو بدون اینترنت)
  path: ^1.9.0                  # برای پیدا کردن مسیر ذخیره دیتابیس

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # فعال کردن پوشه عکس‌ها (برای آینده اگر خواستی عکس به برنامه اضافه کنی)
  # assets:
  #   - assets/images/

  # فعال کردن پوشه فونت‌ها
  fonts:
    - family: Peyda  # نامی که در کدهای فلاتر (style: TextStyle(fontFamily: 'Peyda')) استفاده می‌کنی
      fonts:
        - asset: assets/fonts/Peyda-Regular.ttf
          weight: 400
        - asset: assets/fonts/Peyda-Medium.ttf
          weight: 500
        - asset: assets/fonts/Peyda-Bold.ttf
          weight: 700