name: esalat_car
description: "اپلیکیشن اصالت خودرو"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # پکیج‌های اضافه شده برای پروژه شما
  http: ^1.2.1                  # برای ارتباط با API سرور
  shared_preferences: ^2.2.3    # برای ذخیره کوکی/توکن لاگین
  provider: ^6.1.2              # برای مدیریت تم تاریک/روشن

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # فعال کردن پوشه فونت‌ها
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Regular.ttf
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700